// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See VVentus.h for the primary calling header

#include "verilated.h"

#include "VVentus__Syms.h"
#include "VVentus___024root.h"

VL_INLINE_OPT void VVentus___024root___nba_sequent__TOP__2(VVentus___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    VVentus__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VVentus___024root___nba_sequent__TOP__2\n"); );
    // Body
    vlSelf->GPGPU_top__DOT__cta__DOT__cta_sche__DOT__gpu_interface_i__DOT__dispatch2cu_wf_tag_dispatch_i 
        = vlSelf->__Vdly__GPGPU_top__DOT__cta__DOT__cta_sche__DOT__gpu_interface_i__DOT__dispatch2cu_wf_tag_dispatch_i;
    vlSelf->GPGPU_top__DOT__cta__DOT__cta_sche__DOT__gpu_interface_i_io_cu2dispatch_wf_done 
        = (((IData)(vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1.io_CTArsp_valid) 
            << 1U) | (IData)(vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper.io_CTArsp_valid));
    vlSelf->GPGPU_top__DOT__cta__DOT__cta_sche__DOT__gpu_interface_i__DOT___GEN_52 
        = ((IData)(vlSelf->GPGPU_top__DOT__cta__DOT__cta_sche__DOT__gpu_interface_i__DOT___GEN_48)
            ? ((1U & (IData)(vlSelf->GPGPU_top__DOT__cta__DOT__cta_sche__DOT__gpu_interface_i__DOT__allocator_cu_id_out_i))
                ? (IData)(vlSelf->GPGPU_top__DOT__cta__DOT__cta_sche__DOT__gpu_interface_i__DOT__dispatch2cu_wf_tag_dispatch_handlers_1)
                : (IData)(vlSelf->GPGPU_top__DOT__cta__DOT__cta_sche__DOT__gpu_interface_i__DOT__dispatch2cu_wf_tag_dispatch_handlers_0))
            : (IData)(vlSelf->GPGPU_top__DOT__cta__DOT__cta_sche__DOT__gpu_interface_i__DOT__dispatch2cu_wf_tag_dispatch_i));
    vlSelf->GPGPU_top__DOT__cta__DOT__cta_sche__DOT__gpu_interface_i__DOT___GEN_77 
        = ((8U == (IData)(vlSelf->GPGPU_top__DOT__cta__DOT__cta_sche__DOT__gpu_interface_i__DOT__alloc_st))
            ? (IData)(vlSelf->GPGPU_top__DOT__cta__DOT__cta_sche__DOT__gpu_interface_i__DOT___GEN_52)
            : (IData)(vlSelf->GPGPU_top__DOT__cta__DOT__cta_sche__DOT__gpu_interface_i__DOT__dispatch2cu_wf_tag_dispatch_i));
}

void VVentus___024root___nba_sequent__TOP__0(VVentus___024root* vlSelf);
void VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__0(VVentus_SM_wrapper* vlSelf);
void VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__1(VVentus_SM_wrapper* vlSelf);
void VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__2(VVentus_SM_wrapper* vlSelf);
void VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__0(VVentus_SM_wrapper* vlSelf);
void VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__1(VVentus_SM_wrapper* vlSelf);
void VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__icache__DOT__tagAccess__0(VVentus_L1TagAccess* vlSelf);
void VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__icache__DOT__tagAccess__0(VVentus_L1TagAccess* vlSelf);
void VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1__0(VVentus_ScalarFPU_1* vlSelf);
void VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2__0(VVentus_ScalarFPU_1* vlSelf);
void VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3__0(VVentus_ScalarFPU_1* vlSelf);
void VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1__0(VVentus_ScalarFPU_1* vlSelf);
void VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2__0(VVentus_ScalarFPU_1* vlSelf);
void VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3__0(VVentus_ScalarFPU_1* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_1__0(VVentus_ArrayMultiplier* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier__1(VVentus_ArrayMultiplier* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_2__0(VVentus_ArrayMultiplier* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_3__0(VVentus_ArrayMultiplier* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_1__0(VVentus_ArrayMultiplier* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_2__0(VVentus_ArrayMultiplier* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_3__0(VVentus_ArrayMultiplier* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier__0(VVentus_ArrayMultiplier* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier__0(VVentus_ArrayMultiplier* vlSelf);
void VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__dcache__DOT__TagAccess__0(VVentus_L1TagAccess* vlSelf);
void VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__dcache__DOT__TagAccess__0(VVentus_L1TagAccess* vlSelf);
void VVentus_resource_table___nba_sequent__TOP__GPGPU_top__DOT__cta__DOT__cta_sche__DOT__top_resource_table_i__DOT__rt_group__DOT__lds_res_tbl__0(VVentus_resource_table* vlSelf);
void VVentus_resource_table___nba_sequent__TOP__GPGPU_top__DOT__cta__DOT__cta_sche__DOT__top_resource_table_i__DOT__rt_group__DOT__vgpr_res_tbl__0(VVentus_resource_table* vlSelf);
void VVentus_resource_table___nba_sequent__TOP__GPGPU_top__DOT__cta__DOT__cta_sche__DOT__top_resource_table_i__DOT__rt_group__DOT__sgpr_res_tbl__0(VVentus_resource_table* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_3__0(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_3__0(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_2__0(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_2__0(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit__0(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit__0(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_1__0(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_1__0(VVentus_collectorUnit* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_0__0(VVentus_Queue_19* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_0__0(VVentus_Queue_19* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_3__0(VVentus_Queue_19* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_3__0(VVentus_Queue_19* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_2__0(VVentus_Queue_19* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_2__0(VVentus_Queue_19* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_1__0(VVentus_Queue_19* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_1__0(VVentus_Queue_19* vlSelf);
void VVentus___024root___nba_sequent__TOP__1(VVentus___024root* vlSelf);
void VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_0__DOT__FMA__DOT__addPipe__DOT__s1__0(VVentus_FCMA_ADD_s1* vlSelf);
void VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_0__DOT__FMA__DOT__addPipe__DOT__s1__0(VVentus_FCMA_ADD_s1* vlSelf);
void VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__3(VVentus_SM_wrapper* vlSelf);
void VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__4(VVentus_SM_wrapper* vlSelf);
void VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__3(VVentus_SM_wrapper* vlSelf);
void VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__4(VVentus_SM_wrapper* vlSelf);
void VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1__FMA__DOT__addPipe__DOT__s1__0(VVentus_FCMA_ADD_s1* vlSelf);
void VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2__FMA__DOT__addPipe__DOT__s1__0(VVentus_FCMA_ADD_s1* vlSelf);
void VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3__FMA__DOT__addPipe__DOT__s1__0(VVentus_FCMA_ADD_s1* vlSelf);
void VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1__FMA__DOT__addPipe__DOT__s1__0(VVentus_FCMA_ADD_s1* vlSelf);
void VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2__FMA__DOT__addPipe__DOT__s1__0(VVentus_FCMA_ADD_s1* vlSelf);
void VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3__FMA__DOT__addPipe__DOT__s1__0(VVentus_FCMA_ADD_s1* vlSelf);
void VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__icache__DOT__tagAccess__1(VVentus_L1TagAccess* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_1__2(VVentus_ArrayMultiplier* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_2__2(VVentus_ArrayMultiplier* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_3__2(VVentus_ArrayMultiplier* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier__2(VVentus_ArrayMultiplier* vlSelf);
void VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__dcache__DOT__TagAccess__1(VVentus_L1TagAccess* vlSelf);
void VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1__1(VVentus_ScalarFPU_1* vlSelf);
void VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2__1(VVentus_ScalarFPU_1* vlSelf);
void VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3__1(VVentus_ScalarFPU_1* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_0__1(VVentus_Queue_19* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_1__1(VVentus_Queue_19* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_2__1(VVentus_Queue_19* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_3__1(VVentus_Queue_19* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit__1(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_1__1(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_2__1(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_3__1(VVentus_collectorUnit* vlSelf);
void VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__icache__DOT__tagAccess__1(VVentus_L1TagAccess* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_1__2(VVentus_ArrayMultiplier* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_2__2(VVentus_ArrayMultiplier* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_3__2(VVentus_ArrayMultiplier* vlSelf);
void VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier__2(VVentus_ArrayMultiplier* vlSelf);
void VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__dcache__DOT__TagAccess__1(VVentus_L1TagAccess* vlSelf);
void VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1__1(VVentus_ScalarFPU_1* vlSelf);
void VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2__1(VVentus_ScalarFPU_1* vlSelf);
void VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3__1(VVentus_ScalarFPU_1* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_0__1(VVentus_Queue_19* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_1__1(VVentus_Queue_19* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_2__1(VVentus_Queue_19* vlSelf);
void VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_3__1(VVentus_Queue_19* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit__1(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_1__1(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_2__1(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_3__1(VVentus_collectorUnit* vlSelf);
void VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__5(VVentus_SM_wrapper* vlSelf);
void VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__5(VVentus_SM_wrapper* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit__2(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_1__2(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_2__2(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_3__2(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit__2(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_1__2(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_2__2(VVentus_collectorUnit* vlSelf);
void VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_3__2(VVentus_collectorUnit* vlSelf);
void VVentus___024root___nba_sequent__TOP__3(VVentus___024root* vlSelf);

void VVentus___024root___eval_nba(VVentus___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    VVentus__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VVentus___024root___eval_nba\n"); );
    // Body
    if (vlSelf->__VnbaTriggered.at(0U)) {
        VVentus___024root___nba_sequent__TOP__0(vlSelf);
        vlSelf->__Vm_traceActivity[2U] = 1U;
        VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper));
        VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper));
        VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper));
        VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1));
        VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1));
        VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1));
        VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__icache__DOT__tagAccess__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__icache__DOT__tagAccess));
        VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__icache__DOT__tagAccess__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__icache__DOT__tagAccess));
        VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1));
        VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2));
        VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3));
        VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1));
        VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2));
        VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_1));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_1));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_2__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_2));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_2));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_3__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_3));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_3));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_1));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_1));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_2__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_2));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_2));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_3__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_3));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_3));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier));
        VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__dcache__DOT__TagAccess__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__dcache__DOT__TagAccess));
        VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__dcache__DOT__TagAccess__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__dcache__DOT__TagAccess));
        VVentus_resource_table___nba_sequent__TOP__GPGPU_top__DOT__cta__DOT__cta_sche__DOT__top_resource_table_i__DOT__rt_group__DOT__lds_res_tbl__0((&vlSymsp->TOP__GPGPU_top__DOT__cta__DOT__cta_sche__DOT__top_resource_table_i__DOT__rt_group__DOT__lds_res_tbl));
        VVentus_resource_table___nba_sequent__TOP__GPGPU_top__DOT__cta__DOT__cta_sche__DOT__top_resource_table_i__DOT__rt_group__DOT__vgpr_res_tbl__0((&vlSymsp->TOP__GPGPU_top__DOT__cta__DOT__cta_sche__DOT__top_resource_table_i__DOT__rt_group__DOT__vgpr_res_tbl));
        VVentus_resource_table___nba_sequent__TOP__GPGPU_top__DOT__cta__DOT__cta_sche__DOT__top_resource_table_i__DOT__rt_group__DOT__sgpr_res_tbl__0((&vlSymsp->TOP__GPGPU_top__DOT__cta__DOT__cta_sche__DOT__top_resource_table_i__DOT__rt_group__DOT__sgpr_res_tbl));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_3__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_3));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_3__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_3));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_2__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_2));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_2__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_2));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_1));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_1));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_0__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_0));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_0__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_0));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_3__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_3));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_3__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_3));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_2__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_2));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_2__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_2));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_1));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_1));
        VVentus___024root___nba_sequent__TOP__1(vlSelf);
        VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_0__DOT__FMA__DOT__addPipe__DOT__s1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_0__DOT__FMA__DOT__addPipe__DOT__s1));
        VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_0__DOT__FMA__DOT__addPipe__DOT__s1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_0__DOT__FMA__DOT__addPipe__DOT__s1));
        VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__3((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper));
        VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__4((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper));
        VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__3((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1));
        VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__4((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1));
        VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1__FMA__DOT__addPipe__DOT__s1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1__FMA__DOT__addPipe__DOT__s1));
        VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2__FMA__DOT__addPipe__DOT__s1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2__FMA__DOT__addPipe__DOT__s1));
        VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3__FMA__DOT__addPipe__DOT__s1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3__FMA__DOT__addPipe__DOT__s1));
        VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1__FMA__DOT__addPipe__DOT__s1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1__FMA__DOT__addPipe__DOT__s1));
        VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2__FMA__DOT__addPipe__DOT__s1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2__FMA__DOT__addPipe__DOT__s1));
        VVentus_FCMA_ADD_s1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3__FMA__DOT__addPipe__DOT__s1__0((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3__FMA__DOT__addPipe__DOT__s1));
        VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__icache__DOT__tagAccess__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__icache__DOT__tagAccess));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_1__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_1));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_2__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_2));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_3__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier_3));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__mul__DOT__ArrayMultiplier));
        VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__dcache__DOT__TagAccess__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__dcache__DOT__TagAccess));
        VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1));
        VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2));
        VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_0__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_0));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_1__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_1));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_2__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_2));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_3__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__ibuffer__DOT__fifo_3));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_1__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_1));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_2__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_2));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_3__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_3));
        VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__icache__DOT__tagAccess__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__icache__DOT__tagAccess));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_1__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_1));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_2__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_2));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_3__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier_3));
        VVentus_ArrayMultiplier___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__mul__DOT__ArrayMultiplier));
        VVentus_L1TagAccess___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__dcache__DOT__TagAccess__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__dcache__DOT__TagAccess));
        VVentus___024root___nba_sequent__TOP__2(vlSelf);
        VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_1));
        VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_2));
        VVentus_ScalarFPU_1___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__fpu__DOT__fpu__DOT__FPUArray_3));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_0__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_0));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_1__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_1));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_2__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_2));
        VVentus_Queue_19___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_3__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__ibuffer__DOT__fifo_3));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_1__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_1));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_2__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_2));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_3__1((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_3));
        VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__5((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper));
        VVentus_SM_wrapper___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__5((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_1__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_1));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_2__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_2));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_3__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper__pipe__DOT__operand_collector__DOT__collectorUnit_3));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_1__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_1));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_2__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_2));
        VVentus_collectorUnit___nba_sequent__TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_3__2((&vlSymsp->TOP__GPGPU_top__DOT__SM_wrapper_1__pipe__DOT__operand_collector__DOT__collectorUnit_3));
        VVentus___024root___nba_sequent__TOP__3(vlSelf);
    }
}
